apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-x-job-creator-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiap-x-job-creator
  template:
    metadata:
      labels:
        app: fiap-x-job-creator
    spec:
      containers:
      - name: fiap-x-job-creator
        image: danilocassola/fiap-x-job-creator:v1
        env:
        - name: QUEUE_URL
          valueFrom:
                secretKeyRef:
                  name: fiap-x-job-creator-app-secrets
                  key: QUEUE_URL
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: fiap-x-job-creator-app-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: fiap-x-job-creator-app-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: fiap-x-job-creator-app-secrets
              key: AWS_SESSION_TOKEN
        - name: AWS_ACCESS_KEY_ID_SES
          valueFrom:
            secretKeyRef:
              name: fiap-x-job-creator-app-secrets
              key: AWS_ACCESS_KEY_ID_SES
        - name: AWS_SECRET_ACCESS_KEY_SES
          valueFrom:
            secretKeyRef:
              name: fiap-x-job-creator-app-secrets
              key: AWS_SECRET_ACCESS_KEY_SES
        - name: MONGODB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: fiap-x-job-creator-app-secrets
              key: MONGODB_CONNECTION_STRING
        - name: MONGODB_DB_NAME
          valueFrom:
            secretKeyRef:
              name: fiap-x-job-creator-app-secrets
              key: MONGODB_DB_NAME
        - name: BUCKET_VIDEOS_NAME
          valueFrom:
            secretKeyRef:
              name: fiap-x-job-creator-app-secrets
              key: BUCKET_VIDEOS_NAME
        - name: BUCKET_IMAGES_ZIP_NAME
          valueFrom:
            secretKeyRef:
              name: fiap-x-job-creator-app-secrets
              key: BUCKET_IMAGES_ZIP_NAME
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "100m" 