apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fiap-x-sqs-listener-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fiap-x-sqs-listener-app
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
